"""add users header picture

Revision ID: 02748070fadf
Revises: 2a7b9430b222
Create Date: 2018-07-19 15:30:36.163000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02748070fadf'
down_revision = '2a7b9430b222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('header_picutre', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'header_picutre')
    # ### end Alembic commands ###
