"""init migration

Revision ID: 0a3f8cb7a001
Revises: 
Create Date: 2018-06-22 16:16:04.013000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3f8cb7a001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_password', sa.VARCHAR(length=50), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('theme_id', sa.INTEGER(), nullable=True),
    sa.Column('head_id', sa.INTEGER(), nullable=True),
    sa.Column('level', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], [u'theme.theme_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('theme',
    sa.Column('theme_id', sa.INTEGER(), nullable=False),
    sa.Column('theme_name', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('theme_id'),
    sa.UniqueConstraint('theme_name')
    )
    # ### end Alembic commands ###
