"""Post table add column body_html

Revision ID: 307c945b1da0
Revises: 6f1fc358420c
Create Date: 2018-08-03 16:23:41.513000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307c945b1da0'
down_revision = '6f1fc358420c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
