"""add table users and theme

Revision ID: 60f0082d9ee7
Revises: 0a3f8cb7a001
Create Date: 2018-06-22 16:16:51.136000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f0082d9ee7'
down_revision = '0a3f8cb7a001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.Column('theme_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('theme_id'),
    sa.UniqueConstraint('theme_name')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_password', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('theme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['theme.theme_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('theme')
    # ### end Alembic commands ###
